services:
  postgres:
    image: postgres:16-alpine
    container_name: akashcode-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: akashcode
      POSTGRES_PASSWORD: akashcode
      POSTGRES_DB: akashcode_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U akashcode -d akashcode_db']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    driver: local
